- name: git personal setup email
  git_config:
    name: user.email
    scope: global
    value: 'stanislav.codes@gmail.com'
  tags:
    - git-personal
- name: git personal setup name
  git_config:
    name: user.name
    scope: global
    value: 'Stanislav Korchevskyi'
  tags:
    - git-personal
- name: git jsn setup email
  git_config:
    name: user.email
    scope: global
    value: 'stanislav.k.jsn@gmail.com'
  tags:
    - git-jsn
- name: git jsn setup name
  git_config:
    name: user.name
    scope: global
    value: 'Stanislav Korchevskyi'
  tags:
    - git-jsn
- name: git mrw setup email
  git_config:
    name: user.email
    scope: global
    value: 'stanislav.k@myrunway.co.za'
  tags:
    - git-mrw
- name: git mrw setup name
  git_config:
    name: user.name
    scope: global
    value: 'Stanislav Korchevskyi'
  tags:
    - git-mrw
