- name: Install Docker using get.docker.com script
  shell: curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: '{{ username }}'
    groups: docker
    append: yes
  become: yes

- name: Fix Docker config directory ownership (if exists)
  file:
    path: '/home/{{ username }}/.docker'
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0755'
    recurse: yes
  ignore_errors: yes

- name: Start and enable Docker service
  systemd:
    name: docker.service
    state: started
    enabled: yes
  become: yes

- name: Start and enable containerd service
  systemd:
    name: containerd.service
    state: started
    enabled: yes

- name: Warn about group membership
  debug:
    msg: 'Note: You may need to log out and back in for docker group membership to take effect'
