- name: Update dnf cache
  dnf:
    update_cache: yes
  tags:
    - apps
    - install

- name: Install applications
  dnf:
    name: '{{ apps_to_install }}'
    state: present
  register: install_result
  tags:
    - apps
    - install

- name: Display installation results
  debug:
    msg: 'Successfully installed: {{ install_result.results | length }} packages'
  when: install_result is succeeded
  tags:
    - apps
    - install