- name: installing stow
  dnf: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: cloning .dotfiles
  git:
    repo: 'git@github.com:stanislavcodes/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: stow dotfiles
  become: true
  shell: cd {{ lookup('env', 'HOME') }}/.dotfiles && chmod +x ./fedora && ./fedora
  tags:
    - install
    - dotfiles
    - stow
