- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "stanislav.codes@gmail.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Stanislav Korchevskyi"
  tags:
  - git-personal
- name: Git JSN setup email
  git_config:
    name: user.email
    scope: global
    value: "stanislav.k.jsn@gmail.com"
  tags:
  - git-jsn
- name: Git JSN setup name
  git_config:
    name: user.name
    scope: global
    value: "Stanislav Korchevskyi"
  tags:
  - git-jsn
- name: Git MRW setup email
  git_config:
    name: user.email
    scope: global
    value: "stanislav.k@myrunway.co.za"
  tags:
  - git-mrw
- name: Git MRW setup name
  git_config:
    name: user.name
    scope: global
    value: "mpaulson"
  tags:
  - git-mrw