- name: Advent Of Code exists
  stat:
    path: "{{ personal }}/advent-of-code"
  register: aoc
  tags:
    - install
    - dotfiles
    - personal-project
  
- name: Personal Project Advent Of Code
  ansible.builtin.git:
    repo: 'git@github.com:stanislavcodes/advent-of-code.git'
    bare: true
    dest: "{{ personal }}/advent-of-code"
  tags:
    - install
    - dotfiles
    - personal-project
  when: aoc.stat.exists == False